version: '3.7'

services:
  app:
    build: .
    volumes: 
      - .:/usr/app
    ports:
      - '3333:3333'
    depends_on:
      - db
    container_name: app
    env_file:
      - .env

  db:
    container_name: db
    image: postgres:10.5
    environment:
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
        - '5432:5432'
    volumes:
        - .:/usr/src/app
    restart: always
